version: "3.8"

services:
  postgres:
    image: postgres:17.2-alpine
    container_name: my_postgres_1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MAX_CONNECTIONS: 200 
    ports:
      - "5432:5432"
    networks:
      - backend

  g4f:
    networks:
          - backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    command: ["g4f", "api", "--ignored-providers", "Liaobots"]

  chatbot:
    networks:
        - backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CHAINLIT_AUTH_SECRET=${CHAINLIT_AUTH_SECRET}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: |
      uvicorn main:app --host 0.0.0.0 --port 8000
  
  chatbot-client:
    networks:
        - backend
    image: omidima/chainlit-frontend:latest
    environment:
      - INTERFACE_LANG=${INTERFACE_LANG:-en}
    ports:
      - "4173"

  nnginx:
    image: nginx:1.25-alpine
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chatbot
      - chatbot-client
    networks:
      - backend

networks:
  backend:
    driver: bridge